### ISSUE TITLE
为何在本地的mac机子上安装tunnel失败？

### ISSUE THREAD

**Issue by luckypoem** [ccsexyz/tunnel#1]
yudeMacBook-Air:gopath brite$ go get -u -v github.com/ccsexyz/tunnel
github.com/ccsexyz/tunnel (download)
github.com/ccsexyz/rawcon (download)
github.com/google/gopacket (download)
github.com/ccsexyz/shadowsocks-go (download)
github.com/Yawning/chacha20 (download)
github.com/ccsexyz/mux (download)
github.com/ccsexyz/utils (download)
github.com/ccsexyz/mux
# github.com/ccsexyz/mux
src/github.com/ccsexyz/mux/mux.go:370: undefined: net.Buffers
yudeMacBook-Air:gopath brite$ ls /usr/local/go/bin/
go	godoc	gofmt
yudeMacBook-Air:gopath brite$

**Comment by ccsexyz** [comment]
@luckypoem net.Buffers是go1.8加入的新特性,所以需要go1.8才能编译.

**Comment by luckypoem** [comment]
我删除旧版，安装了1.8.1版，但是
yudeMacBook-Air:gopath brite$ go get -u -v github.com/ccsexyz/tunnel
package github.com/ccsexyz/tunnel: directory "/usr/local/go/gopath/src/github.com/ccsexyz/tunnel" is not using a known version control system
yudeMacBook-Air:gopath brite$ which git
/usr/local/bin/git
yudeMacBook-Air:gopath brite$ go version
go version go1.8.1 darwin/amd64
yudeMacBook-Air:gopath brite$

怎么解决？谢谢你

**Comment by ccsexyz** [comment]
把tunnel这个目录删掉重新go get一次试试看

**Comment by luckypoem** [comment]
hi.

yudeMacBook-Air:gopath brite$ sudo go get -u -v github.com/ccsexyz/tunnel
github.com/ccsexyz/tunnel (download)
github.com/ccsexyz/rawcon (download)
github.com/google/gopacket (download)
github.com/ccsexyz/shadowsocks-go (download)
github.com/Yawning/chacha20 (download)
github.com/ccsexyz/mux (download)
github.com/ccsexyz/utils (download)
github.com/google/gopacket
github.com/ccsexyz/utils
github.com/Yawning/chacha20
github.com/ccsexyz/shadowsocks-go/redir
github.com/ccsexyz/mux
github.com/ccsexyz/shadowsocks-go/shadowsocks
github.com/google/gopacket/layers
github.com/google/gopacket/pcap
github.com/ccsexyz/rawcon
github.com/ccsexyz/tunnel
yudeMacBook-Air:gopath brite$ which tunnel
yudeMacBook-Air:gopath brite$ ls
yudeMacBook-Air:gopath brite$ ls /usr/local/go/bin/
go	godoc	gofmt
yudeMacBook-Air:gopath brite$

tunnel装好了吗？怎么找不到它的可执行文件？

**Comment by ccsexyz** [comment]
在 $GOPATH/bin 下面

**Comment by luckypoem** [comment]
找到了。但是，

yudeMacBook-Air:bin brite$ ~/go/bin/tunnel ccsexyz-tunnel.json
2017/05/14 18:17:03 incorrect bind address
yudeMacBook-Air:bin brite$ cat ccsexyz-tunnel.json
{
    "type": "server",
    "localaddr": "127.0.0.1:7676",
    "remoteaddr": "my-vps-ip:6666",
    "method": "aes-256-cfb",
    "password": "iloveson"
}
yudeMacBook-Air:bin brite$

怎么解决“incorrect bind address”？

**Comment by ccsexyz** [comment]
@luckypoem 看起来是没找到地址是 127.0.0.1 的接口,非 Linux 下的服务端这边还有一些 Bug。但是最近没时间修这个 Bug 了。直接在 Linux 服务器上跑服务端，Mac 下跑客户端吧，我测试过是没问题的。

**Comment by luckypoem** [comment]
我是“在 Linux 服务器上跑服务端，Mac 下跑客户端”啊。你的意思是说你已经提供了mac下的客户端？我在此 https://github.com/ccsexyz/tunnel/releases 没看到啊

**Comment by ccsexyz** [comment]
服务端和客户端是一个可执行文件,用 type 字段区分,我更新下 Readme 吧

**Comment by luckypoem** [comment]
不过通常，服务器上的可执行文件下载到mac上是运行不了的啊。可否提供mac下的客户端下载呢？

**Comment by ccsexyz** [comment]
额，我一会儿编译一个上传吧。

**Comment by luckypoem** [comment]
hi.

yudeMacBook-Air:downloads brite$ sudo mv tunnel_darwin_amd64 ccsexyz-tunnel
yudeMacBook-Air:downloads brite$ ./ccsexyz-tunnel 
usage: tunnel configfile
yudeMacBook-Air:downloads brite$ ./ccsexyz-tunnel ccsexyz-tunnel.json
2017/05/15 12:42:15 incorrect bind address
yudeMacBook-Air:downloads brite$

仍然提示“incorrect bind address”。为何？

**Comment by ccsexyz** [comment]
蛤，发下你的配置文件看看，确定type字段不是server吗？

**Comment by luckypoem** [comment]
我把type字段改成client,不过翻不了墙。
服务器端在运行中：
root@localhost:~# ps aux|grep tunnel
root     25247  0.0  0.0  11740   900 pts/32   S+   05:51   0:00 grep tunnel
root     27627  0.0  0.2 180324  2704 ?        Sl   May14   0:47 tunnel ccsexyz-tunnel.json
root@localhost:~#

客户端：
yudeMacBook-Air:downloads brite$ cat ccsexyz-tunnel.json
{
    "type": "client",
    "localaddr": "127.0.0.1:7676",
    "remoteaddr": "my-vps-ip:6666",
    "method": "aes-256-cfb",
    "password": "iloveson"
}

yudeMacBook-Air:downloads yuming$ ./ccsexyz-tunnel ccsexyz-tunnel.json

难道是加密方法不支持aes-256-cfb？

**Comment by ccsexyz** [comment]
客户端也要用root权限运行,mac下还要设置pf规则过滤RST报文,参考[kcpraw](https://github.com/ccsexyz/kcpraw)
