### ISSUE TITLE
error

### ISSUE THREAD

**Issue by githubtc** [ccsexyz/tunnel#3]
panic: reflect: call of reflect.Value.Int on zero Value

goroutine 6 [running]:
reflect.Value.Int(0x0, 0x0, 0x0, 0x5dab16)
        /usr/lib/go-1.9/src/reflect/value.go:908 +0x141
golang.org/x/net/internal/socket.socketOf(0x6bb5a0, 0xc42000c058, 0x7f1eecec7000, 0x0, 0x3)
        /root/go/src/golang.org/x/net/internal/socket/reflect.go:57 +0x200
golang.org/x/net/internal/socket.(*Option).set(0xc42001a3e0, 0xc420046940, 0xc420039678, 0x10, 0x10, 0x5dafa8, 0x3)
        /root/go/src/golang.org/x/net/internal/socket/reflect.go:37 +0x3b
golang.org/x/net/internal/socket.(*Option).Set(0xc42001a3e0, 0xc420046940, 0xc420039678, 0x10, 0x10, 0x5a79c0, 0x0)
        /root/go/src/golang.org/x/net/internal/socket/socket.go:69 +0x150
golang.org/x/net/ipv4.(*sockOpt).setAttachFilter(0xc42001a3e0, 0xc420046940, 0xc420039778, 0xb, 0xb, 0x75abe0ca, 0x1a52fc998298bad2)
        /root/go/src/golang.org/x/net/ipv4/sys_bpf.go:22 +0x82
golang.org/x/net/ipv4.(*sockOpt).setBPF(0xc42001a3e0, 0xc420046940, 0xc420039778, 0xb, 0xb, 0x1, 0xc420046940)
        /root/go/src/golang.org/x/net/ipv4/sockopt_posix.go:70 +0x53
golang.org/x/net/ipv4.(*dgramOpt).SetBPF(0xc420039878, 0xc420039778, 0xb, 0xb, 0xc42000c058, 0x10)
        /root/go/src/golang.org/x/net/ipv4/dgramopt.go:264 +0xaa
github.com/ccsexyz/rawcon.(*Raw).ListenRAW(0xc420064320, 0xc420018640, 0xf, 0x0, 0x0, 0x0)
        /root/go/src/github.com/ccsexyz/rawcon/raw_linux.go:549 +0x2ff
github.com/ccsexyz/kcp-go-raw.ListenRAW(0xc420018640, 0xf, 0xc420018653, 0xb, 0x0, 0xc420064320, 0xc42006e270, 0x182, 0x593400, 0xc420046890)
        /root/go/src/github.com/ccsexyz/kcp-go-raw/sess.go:155 +0x679
main.RunRemoteServer(0xc42006e1e0)
        /root/go/src/github.com/ccsexyz/tunnel/server.go:22 +0x122
main.main.func1(0xc420018670, 0xc42006e1e0)
        /root/go/src/github.com/ccsexyz/tunnel/main.go:62 +0x9e
created by main.main
        /root/go/src/github.com/ccsexyz/tunnel/main.go:57 +0x6fc

**Comment by ccsexyz** [comment]
please provide the parameters for the program.
