### ISSUE TITLE
slice bounds out of range

### ISSUE THREAD

**Issue by apple601601601** [ccsexyz/tunnel#5]
2017/11/15 00:07:11.936853 local.go:44: create tunnel from 192.168.1.54:64238 -> [::]:7777 to 192.168.1.201:42716 -> xxx.xxx.xxx.xxx:7777
panic: runtime error: slice bounds out of range

goroutine 19 [running]:
github.com/ccsexyz/utils.(*FecConn).Write(0xc42011cd20, 0xc42016e000, 0x514, 0x514, 0x514, 0x0, 0x0)
        C:/WhyGo/src/github.com/ccsexyz/utils/conn.go:351 +0x25c
github.com/ccsexyz/utils.PipeForUDPServer.func1(0x6c7480, 0xc42011cd20, 0x6c74e0, 0xc4200ac140, 0xc42016a060)
        C:/WhyGo/src/github.com/ccsexyz/utils/net.go:107 +0x189
created by github.com/ccsexyz/utils.PipeForUDPServer
        C:/WhyGo/src/github.com/ccsexyz/utils/net.go:112 +0x15c

**Comment by apple601601601** [comment]
Issue solved by upscaling the mtu to 1400.
Thanks.

**Comment by ccsexyz** [comment]
fixed https://github.com/ccsexyz/utils/commit/d69f323742a15fe5cad7da6938d6fea67997df5b.
